apiVersion: v1
kind: Pod
metadata:
  name: bb-02
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello $NAME, your color is $COLOR, your country is $COUNTRY" && sleep 3600']
    env:
    - name: NAME
      value: Paweł
    - name: COLOR
      value: blue
    - name: COUNTRY
      value: Poland

