apiVersion: v1
kind: Pod
metadata:
  name: bb-04
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello $NAME, your color is $COLOR, your country is $COUNTRY" && sleep 3600']
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: cm-03
          key: name
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: cm-03
          key: color
    - name: COUNTRY
      valueFrom:
        configMapKeyRef:
          name: cm-03
          key: country

