apiVersion: v1
kind: Pod
metadata:
  name: bb-05
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello $NAME" && sleep 3600']
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: cm-03
          key: name
    volumeMounts:      
    - name: vol1
      mountPath: /tmp/vol1
  restartPolicy: Always
  volumes:
  - name: vol1
    emptyDir: {}


