apiVersion: v1
kind: Pod
metadata:
  name: bb-07
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello" && sleep 3600']
    volumeMounts:      
    - name: vol1
      mountPath: /etc/config
  restartPolicy: Always
  volumes:
  - name: vol1
    configMap:
      name: cm-03

