apiVersion: v1
kind: Pod
metadata:
  name: bb-09
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:      
    - name: vol1
      mountPath: /etc/conf
  restartPolicy: Always
  volumes:
  - name: vol1
    configMap:
      name: config
