apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb
  name: bb-04
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: haproxy
    image: haproxy:1.7
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: vol1
      mountPath: /usr/local/etc/haproxy/haproxy.cfg
      readOnly: true
  volumes:
  - name: vol1
    configMap:
      name: haproxy-cm

