apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-01
spec:
  storageClassName: local-storage # matches PV storage class name
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 210Mi

