apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-03
  name: pod-03
spec:
  nodeName: k8s-092020-3t9ao
  containers:
  - image: busybox
    name: bb-pod-03
    command: [/bin/sh, -c, while true; do sleep 5; done]
    volumeMounts:
    - name: my-storage
      mountPath: /foo
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: pvc-01

