apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-04
  name: pod-04
spec:
  containers:
  - image: busybox
    name: bb-pvc
    command: [/bin/sh, -c, while true; do sleep 5; done]
    volumeMounts:
    - name: my-storage
      mountPath: /foo
  nodeName: <put name here>
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc

