apiVersion: v1
kind: Pod
metadata:
  name: bb-01
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'sleep 3600']
    env:
    - name: MY_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret-01
          key: myKey

