apiVersion: v1
kind: Pod
metadata:
  name: bb-02
  labels:
    app: my-bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello Paweł" && sleep 3600']

