apiVersion: v1
kind: Pod
metadata:
  name: bb-03
  labels:
    app: bb
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello Paweł" && sleep 10']
  restartPolicy: Never
