apiVersion: v1
kind: Pod
metadata:
  name: bb-01
spec:
  containers:
  - name: bb
    image: busybox
    command: ["sh", "-c", "echo qwerty && sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "300m"
