apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
  name: workshop
spec:
  type: NodePort
  ports:
  - port: 9010
    protocol: TCP
    targetPort: 8080
  selector:
    app: workshop

