apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"workshop","namespace":"ns14"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"9001"}],"image":"lewap/workshop-app:0.0.2","livenessProbe":{"httpGet":{"path":"/health","port":9001},"initialDelaySeconds":5,"periodSeconds":5},"name":"lewap","ports":[{"containerPort":80}],"readinessProbe":{"httpGet":{"path":"/busy","port":9001},"initialDelaySeconds":2,"periodSeconds":2},"resources":{"limits":{"cpu":"300m","memory":"250Mi"},"requests":{"cpu":"150m","memory":"125Mi"}}}]}}}}
  creationTimestamp: "2020-09-29T07:23:03Z"
  generation: 5
  name: workshop
  namespace: ns14
  resourceVersion: "228172"
  selfLink: /apis/apps/v1/namespaces/ns14/deployments/workshop
  uid: 836ef16f-fee3-4f49-83aa-e7a1dfdf6481
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: lewap/workshop-app:0.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: lewap
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /busy
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 300m
            memory: 250Mi
          requests:
            cpu: 150m
            memory: 125Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
